/* ChatGPT Ref: components/kanjiData.js */

const kanjiData= [
  { ktype: 'verb', kanji: 'くれる', translation: 'give', romaji: 'kureru' },
  { ktype: 'verb', kanji: 'さす', translation: 'point', romaji: 'sasu' },
  { ktype: 'verb', kanji: 'おく', translation: 'put', romaji: 'oku' },
  { ktype: 'verb', kanji: 'かく', translation: 'write', romaji: 'kaku' },
  { ktype: 'verb', kanji: 'よむ', translation: 'read', romaji: 'yomu' },
  { ktype: 'verb', kanji: 'みる', translation: 'watch', romaji: 'miru' },
  { ktype: 'verb', kanji: 'きく', translation: 'listen', romaji: 'kiku' },
  { ktype: 'verb', kanji: 'いう', translation: 'say', romaji: 'iu' },
  { ktype: 'verb', kanji: 'する', translation: 'do', romaji: 'suru' },
  { ktype: 'verb', kanji: 'くる', translation: 'come', romaji: 'kuru' },
  { ktype: 'verb', kanji: 'あう', translation: 'meet', romaji: 'au' },
  { ktype: 'verb', kanji: '打つ', translation: 'hit', romaji: 'utsu' },
  { ktype: 'verb', kanji: '取る', translation: 'take', romaji: 'toru' },
  { ktype: 'verb', kanji: '呼ぶ', translation: 'call', romaji: 'yobu' },
  { ktype: 'verb', kanji: '急ぐ', translation: 'hurry', romaji: 'isogu' },
  { ktype: 'verb', kanji: '変える', translation: 'change', romaji: 'kaeru' },
  { ktype: 'verb', kanji: '集める', translation: 'collect', romaji: 'atsumeru' },
  { ktype: 'verb', kanji: '続く', translation: 'continue', romaji: 'tsuzuku' },
  { ktype: 'verb', kanji: '戻る', translation: 'return', romaji: 'modoru' },
  { ktype: 'verb', kanji: '借りる', translation: 'borrow', romaji: 'kariru' },
  { ktype: 'verb', kanji: '返す', translation: 'return', romaji: 'kaesu' },
  { ktype: 'verb', kanji: '覚える', translation: 'remember', romaji: 'oboeru' },
  { ktype: 'verb', kanji: '忘れる', translation: 'forget', romaji: 'wasureru' },
  { ktype: 'verb', kanji: '洗う', translation: 'wash', romaji: 'arau' }
]


const dataPacks = {

kanjiData_verbPack_01 : [
  { ktype: 'verb', kanji: 'くれる', translation: 'give', romaji: 'kureru' },
  { ktype: 'verb', kanji: 'さす', translation: 'point', romaji: 'sasu' },
  { ktype: 'verb', kanji: 'おく', translation: 'put', romaji: 'oku' },
  { ktype: 'verb', kanji: 'かく', translation: 'write', romaji: 'kaku' },
  { ktype: 'verb', kanji: 'よむ', translation: 'read', romaji: 'yomu' },
  { ktype: 'verb', kanji: 'みる', translation: 'watch', romaji: 'miru' },
  { ktype: 'verb', kanji: 'きく', translation: 'listen', romaji: 'kiku' },
  { ktype: 'verb', kanji: 'いう', translation: 'say', romaji: 'iu' },
  { ktype: 'verb', kanji: 'する', translation: 'do', romaji: 'suru' },
  { ktype: 'verb', kanji: 'くる', translation: 'come', romaji: 'kuru' },
  { ktype: 'verb', kanji: 'あう', translation: 'meet', romaji: 'au' },
  { ktype: 'verb', kanji: '打つ', translation: 'hit', romaji: 'utsu' },
  { ktype: 'verb', kanji: '取る', translation: 'take', romaji: 'toru' },
  { ktype: 'verb', kanji: '呼ぶ', translation: 'call', romaji: 'yobu' },
  { ktype: 'verb', kanji: '急ぐ', translation: 'hurry', romaji: 'isogu' },
  { ktype: 'verb', kanji: '変える', translation: 'change', romaji: 'kaeru' },
  { ktype: 'verb', kanji: '集める', translation: 'collect', romaji: 'atsumeru' },
  { ktype: 'verb', kanji: '続く', translation: 'continue', romaji: 'tsuzuku' },
  { ktype: 'verb', kanji: '戻る', translation: 'return', romaji: 'modoru' },
  { ktype: 'verb', kanji: '借りる', translation: 'borrow', romaji: 'kariru' },
  { ktype: 'verb', kanji: '返す', translation: 'return', romaji: 'kaesu' },
  { ktype: 'verb', kanji: '覚える', translation: 'remember', romaji: 'oboeru' },
  { ktype: 'verb', kanji: '忘れる', translation: 'forget', romaji: 'wasureru' },
  { ktype: 'verb', kanji: '洗う', translation: 'wash', romaji: 'arau' },
  { ktype: 'verb', kanji: '着る', translation: 'wear', romaji: 'kiru' },
  { ktype: 'verb', kanji: '脱ぐ', translation: 'take off', romaji: 'nugu' },
  { ktype: 'verb', kanji: '調べる', translation: 'investigate', romaji: 'shiraberu' },
  { ktype: 'verb', kanji: '決める', translation: 'decide', romaji: 'kimeru' },
  { ktype: 'verb', kanji: '乗る', translation: 'ride', romaji: 'noru' },
  { ktype: 'verb', kanji: '降りる', translation: 'get off', romaji: 'oriru' },
  { ktype: 'verb', kanji: '示す', translation: 'indicate', romaji: 'shimesu' },
  { ktype: 'verb', kanji: '残る', translation: 'remain', romaji: 'nokoru' },
  { ktype: 'verb', kanji: '投げる', translation: 'throw', romaji: 'nageru' },
  { ktype: 'verb', kanji: '保つ', translation: 'keep', romaji: 'tamotsu' },
  { ktype: 'verb', kanji: '止まる', translation: 'stop', romaji: 'tomaru' },
  { ktype: 'verb', kanji: '動く', translation: 'move', romaji: 'ugoku' },
  { ktype: 'verb', kanji: '押す', translation: 'push', romaji: 'osu' },
  { ktype: 'verb', kanji: '引く', translation: 'pull', romaji: 'hiku' },
  { ktype: 'verb', kanji: '考える', translation: 'think', romaji: 'kangaeru' },
  { ktype: 'verb', kanji: '認める', translation: 'recognize', romaji: 'mitomeru' },
  { ktype: 'verb', kanji: '得る', translation: 'gain', romaji: 'eru' },
  { ktype: 'verb', kanji: '向く', translation: 'face', romaji: 'muku' },
  { ktype: 'verb', kanji: '運ぶ', translation: 'carry', romaji: 'hakobu' },
  { ktype: 'verb', kanji: '感じる', translation: 'feel', romaji: 'kanjiru' },
  { ktype: 'verb', kanji: '望む', translation: 'hope', romaji: 'nozomu' },
  { ktype: 'verb', kanji: '拾う', translation: 'pick up', romaji: 'hirou' },
  { ktype: 'verb', kanji: '触る', translation: 'touch', romaji: 'sawaru' },
  { ktype: 'verb', kanji: '数える', translation: 'count', romaji: 'kazoeru' },
  { ktype: 'verb', kanji: '比べる', translation: 'compare', romaji: 'kuraberu' },
  { ktype: 'verb', kanji: '足る', translation: 'be enough', romaji: 'taru' },
  { ktype: 'verb', kanji: '祈る', translation: 'pray', romaji: 'inoru' },
  { ktype: 'verb', kanji: '信じる', translation: 'believe', romaji: 'shinjiru' }
],

kanjiData_verbPack_02 : [
  { ktype: 'verb', kanji: '行く', translation: 'go', romaji: 'iku' },
  { ktype: 'verb', kanji: '来る', translation: 'come', romaji: 'kuru' },
  { ktype: 'verb', kanji: '見る', translation: 'see', romaji: 'miru' },
  { ktype: 'verb', kanji: '聞く', translation: 'hear', romaji: 'kiku' },
  { ktype: 'verb', kanji: '話す', translation: 'talk', romaji: 'hanasu' },
  { ktype: 'verb', kanji: '読む', translation: 'read', romaji: 'yomu' },
  { ktype: 'verb', kanji: '書く', translation: 'write', romaji: 'kaku' },
  { ktype: 'verb', kanji: '学ぶ', translation: 'learn', romaji: 'manabu' },
  { ktype: 'verb', kanji: '食べる', translation: 'eat', romaji: 'taberu' },
  { ktype: 'verb', kanji: '飲む', translation: 'drink', romaji: 'nomu' },
  { ktype: 'verb', kanji: '買う', translation: 'buy', romaji: 'kau' },
  { ktype: 'verb', kanji: '売る', translation: 'sell', romaji: 'uru' },
  { ktype: 'verb', kanji: 'する', translation: 'do', romaji: 'suru' },
  { ktype: 'verb', kanji: '遊ぶ', translation: 'play', romaji: 'asobu' },
  { ktype: 'verb', kanji: '走る', translation: 'run', romaji: 'hashiru' },
  { ktype: 'verb', kanji: '歩く', translation: 'walk', romaji: 'aruku' },
  { ktype: 'verb', kanji: '泳ぐ', translation: 'swim', romaji: 'oyogu' },
  { ktype: 'verb', kanji: '飛ぶ', translation: 'fly', romaji: 'tobu' },
  { ktype: 'verb', kanji: '聞く', translation: 'ask', romaji: 'kiku' },
  { ktype: 'verb', kanji: '知る', translation: 'know', romaji: 'shiru' },
  { ktype: 'verb', kanji: '出る', translation: 'exit', romaji: 'deru' },
  { ktype: 'verb', kanji: '入る', translation: 'enter', romaji: 'hairu' },
  { ktype: 'verb', kanji: '持つ', translation: 'hold', romaji: 'motsu' },
  { ktype: 'verb', kanji: '作る', translation: 'make', romaji: 'tsukuru' },
  { ktype: 'verb', kanji: '住む', translation: 'live', romaji: 'sumu' },
  { ktype: 'verb', kanji: '寝る', translation: 'sleep', romaji: 'neru' },
  { ktype: 'verb', kanji: '座る', translation: 'sit', romaji: 'suwaru' },
  { ktype: 'verb', kanji: '立つ', translation: 'stand', romaji: 'tatsu' },
  { ktype: 'verb', kanji: '会う', translation: 'meet', romaji: 'au' },
  { ktype: 'verb', kanji: '勉強する', translation: 'study', romaji: 'benkyou suru' },
  { ktype: 'verb', kanji: '教える', translation: 'teach', romaji: 'oshieru' },
  { ktype: 'verb', kanji: '開ける', translation: 'open', romaji: 'akeru' },
  { ktype: 'verb', kanji: '閉める', translation: 'close', romaji: 'shimeru' },
  { ktype: 'verb', kanji: '上げる', translation: 'raise', romaji: 'ageru' },
  { ktype: 'verb', kanji: '下げる', translation: 'lower', romaji: 'sageru' },
  { ktype: 'verb', kanji: '始める', translation: 'begin', romaji: 'hajimeru' },
  { ktype: 'verb', kanji: '終わる', translation: 'end', romaji: 'owaru' },
  { ktype: 'verb', kanji: '使う', translation: 'use', romaji: 'tsukau' },
  { ktype: 'verb', kanji: '送る', translation: 'send', romaji: 'okuru' },
  { ktype: 'verb', kanji: '待つ', translation: 'wait', romaji: 'matsu' },
  { ktype: 'verb', kanji: '探す', translation: 'search', romaji: 'sagasu' },
  { ktype: 'verb', kanji: '見つける', translation: 'find', romaji: 'mitsukeru' },
  { ktype: 'verb', kanji: '出す', translation: 'take out', romaji: 'dasu' },
  { ktype: 'verb', kanji: '入れる', translation: 'put in', romaji: 'ireru' },
  { ktype: 'verb', kanji: 'かえる', translation: 'return', romaji: 'kaeru' },
  { ktype: 'verb', kanji: 'つくる', translation: 'create', romaji: 'tsukuru' },
  { ktype: 'verb', kanji: 'とる', translation: 'take', romaji: 'toru' },
  { ktype: 'verb', kanji: 'ある', translation: 'exist (inanimate)', romaji: 'aru' },
  { ktype: 'verb', kanji: 'いる', translation: 'exist (animate)', romaji: 'iru' }
],

kanjiData_verbPack_03 : [ ],
kanjiData_verbPack_04 : [ ],
kanjiData_verbPack_05 : [ ],
kanjiData_verbPack_06 : [ ],
kanjiData_nounPack_01 : [ ],
kanjiData_nounPack_02 : [ ],
kanjiData_nounPack_03 : [ ],
kanjiData_nounPack_04 : [ ],
kanjiData_nounPack_05 : [ ],
kanjiData_nounPack_06 : [ ]

}

export default {kanjiData, dataPacks}
