/* ChatGPT Ref: ./src/components/kanjiData.js */
const kanjiData = [
  { ktype: 'number', kanji: '一', translation: 'one' },
  { ktype: 'number', kanji: '二', translation: 'two' },
  { ktype: 'number', kanji: '三', translation: 'three' },
  { ktype: 'number', kanji: '四', translation: 'four' },
  { ktype: 'number', kanji: '五', translation: 'five' },
  { ktype: 'number', kanji: '六', translation: 'six' },
  { ktype: 'number', kanji: '七', translation: 'seven' },
  { ktype: 'number', kanji: '八', translation: 'eight' },
  { ktype: 'number', kanji: '九', translation: 'nine' },
  { ktype: 'number', kanji: '十', translation: 'ten' },
   { kanji: '食', translation: 'food', ktype: 'food' },
  { kanji: '米', translation: 'rice', ktype: 'food' },
  { kanji: '肉', translation: 'meat', ktype: 'food' },
  { kanji: '野菜', translation: 'vegetables', ktype: 'food' },
  { kanji: '果物', translation: 'fruits', ktype: 'food' },
  { kanji: '牛乳', translation: 'milk', ktype: 'food' },
  { kanji: '卵', translation: 'egg', ktype: 'food' },
  { kanji: '麺', translation: 'noodles', ktype: 'food' },
  { kanji: '味噌', translation: 'miso', ktype: 'food' },
  { kanji: '豆腐', translation: 'tofu', ktype: 'food' },
  { kanji: '煮物', translation: 'stewed dish', ktype: 'food' },
  { kanji: '焼肉', translation: 'barbecue', ktype: 'food' },
  { kanji: '寿司', translation: 'sushi', ktype: 'food' },
  { kanji: '天ぷら', translation: 'tempura', ktype: 'food' },
  { kanji: '鍋', translation: 'hot pot', ktype: 'food' },
  { kanji: 'ラーメン', translation: 'ramen', ktype: 'food' },
  { kanji: 'カレー', translation: 'curry', ktype: 'food' },
  { kanji: 'おにぎり', translation: 'rice ball', ktype: 'food', },
  { kanji: 'お茶', translation: 'tea', ktype: 'food' },
  { kanji: 'コーヒー', translation: 'coffee', ktype: 'food' },
  { kanji: 'ケーキ', translation: 'cake', ktype: 'food' },
  { kanji: 'アイスクリーム', translation: 'ice cream', ktype: 'food' },
  { kanji: 'チョコレート', translation: 'chocolate', ktype: 'food' },
  { kanji: 'パン', translation: 'bread', ktype: 'food' },
  { kanji: 'バター', translation: 'butter', ktype: 'food' },
  { kanji: '酒', translation: 'sake', ktype: 'food' },
  { kanji: 'ビール', translation: 'beer', ktype: 'food' },
  { kanji: 'ワイン', translation: 'wine', ktype: 'food' },
  { kanji: '焼き鳥', translation: 'grilled chicken skewers', ktype: 'food' },
  { kanji: '天丼', translation: 'tempura rice bowl', ktype: 'food' },
  { kanji: 'お好み焼き', translation: 'okonomiyaki', ktype: 'food' },
  { kanji: '刺身', translation: 'sashimi', ktype: 'food' },
  { kanji: 'おでん', translation: 'oden', ktype: 'food' },
  { kanji: '焼きそば', translation: 'yakisoba', ktype: 'food' },
  { kanji: '牛肉', translation: 'beef', ktype: 'food' },
  { kanji: '豚肉', translation: 'pork', ktype: 'food' },
  { kanji: '鶏肉', translation: 'chicken', ktype: 'food' },
  { kanji: 'エビ', translation: 'shrimp', ktype: 'food' },
  { kanji: 'カニ', translation: 'crab', ktype: 'food' },
  { kanji: 'イカ', translation: 'squid', ktype: 'food' },
  { kanji: '貝', translation: 'shellfish', ktype: 'food' },
  { kanji: '野菜', translation: 'vegetables', ktype: 'food' },
  { kanji: '果物', translation: 'fruit', ktype: 'food' }
];


export default kanjiData;
