/* ChatGPT Ref: ./src/components/kanjiData.js */
const kanjiData = [
  { ktype: 'number', kanji: '一', translation: 'one' },
  { ktype: 'number', kanji: '二', translation: 'two' },
  { ktype: 'number', kanji: '三', translation: 'three' },
  { ktype: 'number', kanji: '四', translation: 'four' },
  { ktype: 'number', kanji: '五', translation: 'five' },
  { ktype: 'number', kanji: '六', translation: 'six' },
  { ktype: 'number', kanji: '七', translation: 'seven' },
  { ktype: 'number', kanji: '八', translation: 'eight' },
  { ktype: 'number', kanji: '九', translation: 'nine' },
  { ktype: 'number', kanji: '十', translation: 'ten' },
  { kanji: '食', translation: 'food', ktype: 'food', },
  { kanji: '米', translation: 'rice', ktype: 'food', },
  { kanji: '肉', translation: 'meat', ktype: 'food', },
  { kanji: '野菜', translation: 'vegetables', ktype: 'food', },
  { kanji: '果物', translation: 'fruits', ktype: 'food', },
  { kanji: '牛乳', translation: 'milk', ktype: 'food', },
  { kanji: '卵', translation: 'egg', ktype: 'food', },
  { kanji: '麺', translation: 'noodles', ktype: 'food', },
  { kanji: '味噌', translation: 'miso', ktype: 'food', },
  { kanji: '豆腐', translation: 'tofu', ktype: 'food', },
  { kanji: '煮物', translation: 'stewed dish', ktype: 'food', },
  { kanji: '焼肉', translation: 'barbecue', ktype: 'food', },
  { kanji: '寿司', translation: 'sushi', ktype: 'food', },
  { kanji: '天ぷら', translation: 'tempura', ktype: 'food', },
  { kanji: '鍋', translation: 'hot pot', ktype: 'food', },
  { kanji: 'ラーメン', translation: 'ramen', ktype: 'food', },
  { kanji: 'カレー', translation: 'curry', ktype: 'food', },
  { kanji: 'おにぎり', translation: 'rice ball', ktype: 'food', },
  { kanji: 'お茶', translation: 'tea', ktype: 'food', },
  { kanji: 'コーヒー', translation: 'coffee', ktype: 'food', },
  { kanji: 'ケーキ', translation: 'cake', ktype: 'food', },
  { kanji: 'アイスクリーム', translation: 'ice cream', ktype: 'food', },
  { kanji: 'チョコレート', translation: 'chocolate', ktype: 'food', },
  { kanji: 'パン', translation: 'bread', ktype: 'food', },
  { kanji: 'バター', translation: 'butter', ktype: 'food', },
  { kanji: '酒', translation: 'sake', ktype: 'food', },
  { kanji: 'ビール', translation: 'beer', ktype: 'food', },
  { kanji: 'ワイン', translation: 'wine', ktype: 'food', },
  { kanji: '焼き鳥', translation: 'grilled chicken skewers', ktype: 'food', },
  { kanji: '天丼', translation: 'tempura rice bowl', ktype: 'food', },
  { kanji: 'お好み焼き', translation: 'okonomiyaki', ktype: 'food', },
  { kanji: '刺身', translation: 'sashimi', ktype: 'food', },
  { kanji: 'おでん', translation: 'oden', ktype: 'food', },
  { kanji: '焼きそば', translation: 'yakisoba', ktype: 'food', },
  { kanji: '牛肉', translation: 'beef', ktype: 'food', },
  { kanji: '豚肉', translation: 'pork', ktype: 'food', },
  { kanji: '鶏肉', translation: 'chicken', ktype: 'food', },
  { kanji: 'エビ', translation: 'shrimp', ktype: 'food', },
  { kanji: 'カニ', translation: 'crab', ktype: 'food', },
  { kanji: 'イカ', translation: 'squid', ktype: 'food', },
  { kanji: '貝', translation: 'shellfish', ktype: 'food', },
  { kanji: '野菜', translation: 'vegetables', ktype: 'food', },
  { kanji: '果物', translation: 'fruit', ktype: 'food', },
  { kanji: '蜘蛛', translation: 'spider', ktype: 'animals' },
  { kanji: '犬', translation: 'dog', ktype: 'animals' },
  { kanji: '猫', translation: 'cat', ktype: 'animals' },
  { kanji: '鳥', translation: 'bird', ktype: 'animals' },
  { kanji: '馬', translation: 'horse', ktype: 'animals' },
  { kanji: '牛', translation: 'cow', ktype: 'animals' },
  { kanji: '羊', translation: 'sheep', ktype: 'animals' },
  { kanji: '猿', translation: 'monkey', ktype: 'animals' },
  { kanji: '熊', translation: 'bear', ktype: 'animals' },
  { kanji: '虎', translation: 'tiger', ktype: 'animals' },
  { kanji: '魚', translation: 'fish', ktype: 'animals' },
  { kanji: '蛇', translation: 'snake', ktype: 'animals' },
  { kanji: '象', translation: 'elephant', ktype: 'animals' },
  { kanji: '兎', translation: 'rabbit', ktype: 'animals' },
  { kanji: '獅', translation: 'lion', ktype: 'animals' },
  { kanji: '豚', translation: 'pig', ktype: 'animals' },
  { kanji: '鹿', translation: 'deer', ktype: 'animals' },
  { kanji: '狐', translation: 'fox', ktype: 'animals' },
  { kanji: '狸', translation: 'raccoon', ktype: 'animals' },
  { kanji: '狼', translation: 'wolf', ktype: 'animals' },
  { kanji: '鼠', translation: 'rat', ktype: 'animals' },
  { kanji: '蝶', translation: 'butterfly', ktype: 'animals' },
  { kanji: '蛙', translation: 'frog', ktype: 'animals' },
  { kanji: '蜜蜂', translation: 'bee', ktype: 'animals' },
  { kanji: '獣', translation: 'beast', ktype: 'animals' },
  { kanji: '鷹', translation: 'hawk', ktype: 'animals' },
  { kanji: '鳩', translation: 'pigeon', ktype: 'animals' },
  { kanji: '鴉', translation: 'crow', ktype: 'animals' },
  { kanji: '蝙蝠', translation: 'bat', ktype: 'animals' },
  { kanji: '蛾', translation: 'moth', ktype: 'animals' },
  { kanji: '蜻蛉', translation: 'dragonfly', ktype: 'animals' },
  { kanji: '鯨', translation: 'whale', ktype: 'animals' },
  { kanji: '蝮', translation: 'viper', ktype: 'animals' },
  { kanji: '蝉', translation: 'cicada', ktype: 'animals' },
  { kanji: '鯛', translation: 'sea bream', ktype: 'animals' },
  { kanji: '蟷螂', translation: 'praying mantis', ktype: 'animals' },
  { kanji: '蚕', translation: 'silkworm', ktype: 'animals' },
  { kanji: '螺', translation: 'snail', ktype: 'animals' },
  { kanji: '蛤', translation: 'clam', ktype: 'animals' },
  { kanji: '螃蟹', translation: 'crab', ktype: 'animals' },
  { kanji: '鱈', translation: 'cod', ktype: 'animals' },
  { kanji: '鷹', translation: 'hawk', ktype: 'animals' },
  { kanji: '鴨', translation: 'duck', ktype: 'animals' },
  { kanji: '猪', translation: 'wild boar', ktype: 'animals' },
  { kanji: '鴎', translation: 'seagull', ktype: 'animals' },
  { kanji: '鮭', translation: 'salmon', ktype: 'animals' },
  { kanji: '蛇', translation: 'snake', ktype: 'animals' },
  { kanji: '鼠', translation: 'rat', ktype: 'animals' },
  { kanji: '貓', translation: 'cat', ktype: 'animals' },
  { kanji: '蝙蝠', translation: 'bat', ktype: 'animals' },
    { kanji: '鷺', translation: 'heron', ktype: 'animals' },
  { kanji: '蝶', translation: 'butterfly', ktype: 'animals' },
  { kanji: '机', translation: 'desk', ktype: 'office' },
  { kanji: '椅子', translation: 'chair', ktype: 'office' },
  { kanji: '書類', translation: 'documents', ktype: 'office' },
  { kanji: 'ノートパソコン', translation: 'laptop', ktype: 'office' },
  { kanji: 'モニター', translation: 'monitor', ktype: 'office' },
  { kanji: 'プリンター', translation: 'printer', ktype: 'office' },
  { kanji: 'ファイル', translation: 'file', ktype: 'office' },
  { kanji: 'ホワイトボード', translation: 'whiteboard', ktype: 'office' },
  { kanji: 'スマートフォン', translation: 'smartphone', ktype: 'office' },
  { kanji: 'カレンダー', translation: 'calendar', ktype: 'office' },
  { kanji: '机上灰皿', translation: 'desktop ashtray', ktype: 'office' },
  { kanji: '事務机', translation: 'office desk', ktype: 'office' },
  { kanji: '名刺', translation: 'business card', ktype: 'office' },
  { kanji: '応接セット', translation: 'reception set', ktype: 'office' },
  { kanji: 'サービスベル', translation: 'service bell', ktype: 'office' },
  { kanji: '計算機', translation: 'calculator', ktype: 'office' },
  { kanji: '会議室', translation: 'meeting room', ktype: 'office' },
  { kanji: 'ファックス', translation: 'fax machine', ktype: 'office' },
  { kanji: 'ステープラー', translation: 'stapler', ktype: 'office' },
  { kanji: '定規', translation: 'ruler', ktype: 'office' },
  { kanji: '財布', translation: 'wallet', ktype: 'office' },
  { kanji: 'ハンドクリーム', translation: 'hand cream', ktype: 'office' },
  { kanji: '押印', translation: 'seal stamp', ktype: 'office' },
  { kanji: '事務イス', translation: 'office chair', ktype: 'office' },
  { kanji: 'スキャナー', translation: 'scanner', ktype: 'office' },
  { kanji: 'チェアマット', translation: 'chair mat', ktype: 'office' },
  { kanji: 'データベース', translation: 'database', ktype: 'office' },
  { kanji: 'クリアファイル', translation: 'clear file', ktype: 'office' },
  { kanji: 'モニター', translation: 'monitor', ktype: 'office' },
  { kanji: 'トレイ', translation: 'tray', ktype: 'office' }

];


export default kanjiData;
